class BackupError(Exception):
    pass


class ResourceError(Exception):
    pass
